USE [maestro]
IR
/ * ***** Objeto: Base de datos [Practica3] Fecha del script: 20/09/2019 23:56:06 ***** * /
CREAR  BASE DE DATOS [Practica3]
CONTENCIÓN =  NINGUNO
 EN   PRIMARIA 
( NAME  =  N ' Practica3' , FILENAME  =  N ' C: \ Archivos de programa \ Microsoft SQL Server \ MSSQL12.MSSQLSERVER \ MSSQL \ DATA \ Practica3.mdf' , SIZE = 5120KB, MAXSIZE =  UNLIMITED , FILEGROWTH = 1024KB)
 REGISTRO  EN 
( NOMBRE  =  N ' Practica3_log' , FILENAME  =  N ' C: \ Archivos de programa \ Microsoft SQL Server \ MSSQL12.MSSQLSERVER \ MSSQL \ DATA \ Practica3_log.ldf' , TAMAÑO = 1024KB, MAXSIZE = 2048GB, FILEGROWTH =  10 %)
IR
ALTER  DATABASE [Practica3] SET  COMPATIBILITY_LEVEL  =  120
IR
IF ( 1  =  FULLTEXTSERVICEPROPERTY ( ' IsFullTextInstalled' ))
empezar
EXEC [Practica3]. [Dbo]. [Sp_fulltext_database] @action =  ' enable'
fin
IR
ALTER  DATABASE [Practica3] SET  ANSI_NULL_DEFAULT  OFF 
IR
ALTER  DATABASE [Practica3] SET  ANSI_NULLS  OFF 
IR
ALTER  BASE DE DATOS [Practica3] SET  ANSI_PADDING  OFF 
IR
ALTER  DATABASE [Practica3] SET  ANSI_WARNINGS  OFF 
IR
ALTER  BASE DE DATOS [Practica3] SET  ARITHABORT  OFF 
IR
ALTER  DATABASE [Practica3] SET  AUTO_CLOSE  OFF 
IR
ALTER  BASE DE DATOS [Practica3] SET  AUTO_SHRINK  OFF 
IR
ALTER  DATABASE [Practica3] SET  AUTO_UPDATE_STATISTICS  ON 
IR
ALTER  DATABASE [Practica3] SET  CURSOR_CLOSE_ON_COMMIT  OFF 
IR
ALTER  DATABASE [Practica3] SET  CURSOR_DEFAULT   GLOBAL 
IR
ALTER  DATABASE [Practica3] SET  CONCAT_NULL_YIELDS_NULL  OFF 
IR
ALTER  DATABASE [Practica3] SET  NUMERIC_ROUNDABORT  OFF 
IR
ALTER  BASE DE DATOS [Practica3] SET  QUOTED_IDENTIFIER  OFF 
IR
ALTER  DATABASE [Practica3] SET  RECURSIVE_TRIGGERS  OFF 
IR
ALTER  DATABASE [Practica3] SET   DISABLE_BROKER 
IR
ALTER  DATABASE [Practica3] SET  AUTO_UPDATE_STATISTICS_ASYNC  OFF 
IR
ALTER  DATABASE [Practica3] SET  DATE_CORRELATION_OPTIMIZATION  OFF 
IR
ALTER  BASE DE DATOS [Practica3] SET  CONFIABLE  OFF 
IR
ALTER  BASE DE DATOS [Practica3] SET  ALLOW_SNAPSHOT_ISOLATION  OFF 
IR
ALTER  DATABASE [Practica3] SET  PARAMETERIZATION  SIMPLE 
IR
ALTER  DATABASE [Practica3] SET  READ_COMMITTED_SNAPSHOT  OFF 
IR
ALTER  DATABASE [Practica3] SET HONOR_BROKER_PRIORITY OFF 
IR
ALTER  DATABASE [Practica3] ESTABLECER LA  RECUPERACIÓN  SIMPLE 
IR
ALTER  DATABASE [Practica3] SET   MULTI_USER 
IR
ALTER  DATABASE [Practica3] SET  PAGE_VERIFY  CHECKSUM  
IR
ALTER  DATABASE [Practica3] SET  DB_CHAINING  OFF 
IR
ALTER  DATABASE [Practica3] SET  FILESTREAM (NON_TRANSACTED_ACCESS =  OFF )
IR
ALTER  DATABASE [Practica3] SET TARGET_RECOVERY_TIME =  0 SECONDS
IR
ALTER  BASE DE DATOS [Practica3] SET  DELAYED_DURABILITY  =  DISABLED 
IR
USO [Practica3]
IR
/ * ***** Objeto: Tabla [dbo]. [Compra] Fecha del script: 20/09/2019 23:56:06 ***** * /
SET  ANSI_NULLS  ON
IR
CONFIGURAR  QUIDED_IDENTIFIER  EN
IR
CREAR  TABLA [dbo]. [Compra] (
	[Id_Compra] [int] NO  NULL ,
	[Cantidad] [int] NULL ,
 CLAVE PRIMARIA AGRUPADA
(
	[Id_Compra] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO]
) ENCENDIDO [PRIMARIO]

IR
/ * ***** Objeto: Tabla [dbo]. [Negocio] Fecha de script: 20/09/2019 23:56:06 ***** * /
SET  ANSI_NULLS  ON
IR
CONFIGURAR  QUIDED_IDENTIFIER  EN
IR
CREATE  TABLE [dbo]. [Negocio] (
	[Id_Negocio] [int] NO  NULL ,
	[NombreNegoco] [nvarchar] ( 30 ) NULL ,
	[Lugar] [nvarchar] ( 30 ) NULL ,
 CLAVE PRIMARIA AGRUPADA
(
	[Id_Negocio] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO],
ÚNICO NO CLUSTRADO 
(
	[NombreNegoco] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO]
) ENCENDIDO [PRIMARIO]

IR
/ * ***** Objeto: Tabla [dbo]. [Producto] Fecha del script: 20/09/2019 23:56:06 ***** * /
SET  ANSI_NULLS  ON
IR
CONFIGURAR  QUIDED_IDENTIFIER  EN
IR
CREAR  TABLA [dbo]. [Producto] (
	[Id_Producto] [int] NO  NULL ,
	[NombreProducto] [nvarchar] ( 30 ) NULL ,
	[TipoProdcuto] [nvarchar] ( 30 ) NULL ,
	[PrecioProducto] [int] NULL ,
 CLAVE PRIMARIA AGRUPADA
(
	[Id_Producto] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO],
ÚNICO NO CLUSTRADO 
(
	[NombreProducto] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO],
ÚNICO NO CLUSTRADO 
(
	[TipoProdcuto] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO]
) ENCENDIDO [PRIMARIO]

IR
/ * ***** Objeto: Tabla [dbo]. [Proveedor] Fecha del script: 20/09/2019 23:56:06 ***** * /
SET  ANSI_NULLS  ON
IR
CONFIGURAR  QUIDED_IDENTIFIER  EN
IR
CREATE  TABLE [dbo]. [Proveedor] (
	[Id_Proveedor] [int] NO  NULL ,
	[TipoProveedor] [nvarchar] ( 30 ) NULL ,
 CLAVE PRIMARIA AGRUPADA
(
	[Id_Proveedor] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO],
ÚNICO NO CLUSTRADO 
(
	[TipoProveedor] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO]
) ENCENDIDO [PRIMARIO]

IR
/ * ***** Objeto: Tabla [dbo]. [Ticket] Fecha del script: 20/09/2019 23:56:06 ***** * /
SET  ANSI_NULLS  ON
IR
CONFIGURAR  QUIDED_IDENTIFIER  EN
IR
CREATE  TABLE [dbo]. [Ticket] (
	[id_Ticket] [int] NO  NULL ,
	[Id_Compra] [int] NULL ,
	[Id_Producto] [int] NULL ,
	[Id_Proveedor] [int] NULL ,
	[Id_Negocio] [int] NULL ,
 CLAVE PRIMARIA AGRUPADA
(
	[id_Ticket] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO]
) ENCENDIDO [PRIMARIO]

IR
/ * ***** Objeto: Tabla [dbo]. [Trabajadores] Fecha del script: 20/09/2019 23:56:06 ***** * /
SET  ANSI_NULLS  ON
IR
CONFIGURAR  QUIDED_IDENTIFIER  EN
IR
CREATE  TABLE [dbo]. [Trabajadores] (
	[Id_Empleado] [int] NO  NULL ,
	[Nombre] [nvarchar] ( 30 ) NULL ,
	[Apellido] [nvarchar] ( 30 ) NULL ,
	[Puesto] [nvarchar] ( 30 ) NULL ,
 CLAVE PRIMARIA AGRUPADA
(
	[Id_Empleado] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO],
ÚNICO NO CLUSTRADO 
(
	[Puesto] ASC
) WITH ( PAD_INDEX  =  OFF , STATISTICS_NORECOMPUTE  =  OFF , IGNORE_DUP_KEY  =  OFF , ALLOW_ROW_LOCKS  =  ON , ALLOW_PAGE_LOCKS  =  ON ) ON [PRIMARIO]
) ENCENDIDO [PRIMARIO]

IR
ALTER  TABLE [dbo]. [Entradas]   CON  VERIFICACIÓN ADD   CONSTRAINT [FK_Compra] FOREIGN KEY ([Id_Compra])
REFERENCIAS [dbo]. [Compra] ([Id_Compra])
IR
ALTER  TABLE [dbo]. [Entradas] COMPROBAR  CONSTRAINT [FK_Compra]
IR
ALTER  TABLE [dbo]. [Entradas]   CON  VERIFICACIÓN ADD   CONSTRAINT [Fk_Negocio] FOREIGN KEY ([Id_Negocio])
REFERENCIAS [dbo]. [Negocio] ([Id_Negocio])
IR
ALTER  TABLE [dbo]. [Ticket] VERIFICACIÓN  DE CONTROL [Fk_Negocio]
IR
ALTER  TABLE [dbo]. [Ticket]   WITH  CHECK ADD   CONSTRAINT [FK_Producto] FOREIGN KEY ([Id_Producto])
REFERENCIAS [dbo]. [Producto] ([Id_Producto])
IR
ALTER  TABLE [dbo]. [Entradas] COMPROBAR  CONSTRAINT [FK_Producto]
IR
ALTER  TABLE [dbo]. [Ticket]   WITH  CHECK ADD   CONSTRAINT [Fk_Proveedor] FOREIGN KEY ([Id_Proveedor])
REFERENCIAS [dbo]. [Proveedor] ([Id_Proveedor])
IR
ALTER  TABLE [dbo]. [Entradas] COMPROBAR  CONSTRAINT [Fk_Proveedor]
IR
USE [maestro]
IR
ALTER  DATABASE [Practica3] SET   READ_WRITE 
IR